#!/bin/bash

DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$DIR" || exit 1

for i in $@
do
	LC="$(echo "$i" | sed 's%\([a-z]*\).*%\1%')"
	install -d "$LC" || exit 1
	install -d "$LC"/LC_MESSAGES || exit 1
	msginit -l "$i" -o "$LC"/LC_MESSAGES/redeclipse.po -i redeclipse.pot
done

cd $OLDPWD
